version: '3'
services:
  main:
    tty: true
    ports:
      - 8069:8069
    volumes:
      - ./OpenUpgrade:/OpenUpgrade
      - ./in:/in
      - ./out:/out
      - ./inner-scripts:/scripts
    build:
      context: .
    image: odoo-upgrader
